train:
  _target_: src.datasets.LibrispeechDataset
  part: "train-clean-100"
  max_audio_length: 20.0
  limit: null
  instance_transforms: ${transforms.instance_transforms.train}

val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  max_audio_length: 20.0
  limit: null
  instance_transforms: ${transforms.instance_transforms.inference}
