defaults:
  - model: deepspeech
  - datasets: custom_dir        # Датасет, который читает папку с аудио
  - dataloader: default
  - transforms: no_augs
  - metrics: asr_beam
  - _self_

decoding:
  beam_size: 20
  topk_per_timestep: 50
  beam_threshold: 100.0

text_encoder:
  _target_: src.text_encoder.CTCTextEncoder

inferencer:
  seed: 42
  device: auto
  device_tensors: ["spectrogram"]
  from_pretrained: null          # Путь к model_best.pth
  save_path: "inference_outputs" # Куда сохранять predictions.csv / .txt
  data_dir: null                 # Путь к папке с аудио
  require_text: false            # True - если есть ground truth (считаем метрики), False - просто предсказываем
