defaults:
  - instance/inference@instance_transforms.train
  - instance/inference@instance_transforms.inference

  - batch/none@batch_transforms.train.spectrogram
  - batch/none@batch_transforms.inference.spectrogram

  - _self_
