get_spectrogram:
  _target_: torchaudio.transforms.MelSpectrogram
  sample_rate: 16000
  n_fft: 1024
  win_length: 1024
  hop_length: 256
  f_min: 0
  f_max: 8000
  n_mels: 128

audio:
  _target_: torchvision.transforms.Compose
  transforms: []

spectrogram:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: src.transforms.Log
      eps: 1e-5
    - _target_: src.transforms.Normalize1D
      mean: 0.0
      std: 1.0
